### PR TITLE
Update zh_TW.po

### PR DESCRIPTION
**Pull request by laichiaheng**

### CODE REVIEW

**Comment by laichiaheng** [comment]
@neithern Hi, could you merge this? Thanks.

**Comment by neithern** [comment]
I am outing, will merge tomorrow, thanks.

发自我的iPhone

在 2022年8月3日，12:07，小亨 ***@***.***> 写道：

﻿

@neithern<https://github.com/neithern> Hi, could you merge this? Thanks.

**Comment by neithern** [comment]
Hi, you need to make a new copy of zh_TW.po, not rename zh_CN.po 😂️

**Comment by neithern** [comment]
Added manually.

**Comment by laichiaheng** [comment]
@neithern How to do that? Could you help me do that?

**Comment by neithern** [comment]
> @neithern How to do that? Could you help me to do that?

I merged already, you can modify po/zh_TW.po next time.

**Pull request closed without merging**
