### PR TITLE
Expose metadata as MPRIS property

### PR DESCRIPTION
**Pull request by robertgzr**
- Add MPRIS metadata property
- Add parsed cover uri to music data

### CODE REVIEW

**Comment by neithern** [comment]
Hi, the uri in on_music_cover_uri_parsed() is a temp file uri, used by only by mpris, should not be used by subsequent calls.

**Comment by robertgzr** [comment]
my aim here is to make it possible to retrieve the cover using clients like `playerctl metadata`. currently the only way to get the cover for the currently playing song is to listen to the metadata signal on song change...

**Comment by neithern** [comment]
I mean music.cover_uri should not be set as a temp file, it will be used later when this music be played again.
I added current_cover_uri property for Application, you can use it as same as application's current_music now.

**Comment by neithern** [comment]
Another suggestion: move the private methods to the bottom of the class.

**Comment by neithern** [comment]
Implemented.

**Pull request closed without merging**
